### ISSUE TITLE
Prop or Method  for Specifying Initial Number of Items to Load?

### ISSUE THREAD

**Issue by devolasvegas** [tedconf/react-show-more#13]
Hi! I would like to see if there is a way to make this component display a different number of initial items than is passed with the "by" prop.

By that, I mean that I would like to be able to take a user back to their previous position in my list if they navigate away from, and then back to my list page. Their position would be preserved, and onMore() would still display the same amount of additional items each time the "Load More" button was pressed (in this case, 3 items).

I have a component set up to keep the last position of the list in sessionStorage, and pass that back to the component when navigating back to the page, so the user goes back to their previous position in the list. 

```js
import React, { useState, useEffect } from 'react';
import { graphql, useStaticQuery } from 'gatsby';
import ShowMore from '@tedconf/react-show-more';
import slugify from 'slugify';

import ProjectCard from '../cards/ProjectCard';

const keepListPlace = (items) => {
	const numItems = items.length;
	sessionStorage.setItem('pnrProjectsListPosition', numItems);
};

const ProjectsList = () => {
	const showMoreBy = 3;
	const [listPosition, setListPosition] = useState(undefined);

	useEffect(() => {
		const projectsListPosition = parseInt(
			sessionStorage.getItem('pnrProjectsListPosition')
		);

		if (projectsListPosition) {
			setListPosition(projectsListPosition);
		}
	}, []);

	const data = useStaticQuery(graphql`
		query ProjectsListQuery {
			allMarkdownRemark(
				filter: { frontmatter: { template_key: { eq: "project" } } }
				sort: { fields: frontmatter___date, order: DESC }
			) {
				edges {
					node {
						fields {
							slug
						}
						frontmatter {
							title
							featured_image {
								alt
								image {
									childImageSharp {
										fluid(maxWidth: 1200) {
											...GatsbyImageSharpFluid
										}
									}
								}
							}
						}
					}
				}
			}
		}
	`);

	const { edges: projects } = data.allMarkdownRemark;
	return (
		<ShowMore items={projects} by={showMoreBy}>
			{({ current, onMore, all }) => {
				if (listPosition !== undefined) {
					const combinedPosition = listPosition + showMoreBy;
					current = listPosition ? all.slice(0, combinedPosition) : current;
				}

				return (
					<>
						{current.map(({ node }, i) => {
							const slug = slugify(node.fields.slug);
							return (
								<ProjectCard
									id={slug}
									data={node}
									key={`${node.frontmatter.title}-${i}`}
								/>
							);
						})}
						<div className="has-text-centered">
							<button
								className="button load-more"
								disabled={!onMore}
								onClick={() => {
									keepListPlace(current);
									if (!!onMore) onMore();
								}}
							>
								Load More +
							</button>
						</div>
					</>
				);
			}}
		</ShowMore>
	);
};

export default ProjectsList;

```
As you can see in the child function of the <ShowMore /> component, I'm trying to set `current` based on the count of items from when the user was last on the page. This works to display the correct list of items that was last displayed there, but we then lose the ability to load more items.

**Comment by VinSpee** [comment]
Understood! What kind of component API are you thinking to support this?

**Comment by devolasvegas** [comment]
Hi, @VinSpee ! Maybe just a  prop that takes a number to tell the component how many items to show initially?

**Comment by VinSpee** [comment]
```js
<ShowMore initiallyShowCount={50} items={projects} by={showMoreBy} />
```

something like that @devolasvegas?

**Comment by devolasvegas** [comment]
Yes, @VinSpee, I think that will work just fine! 👌

**Comment by VinSpee** [comment]
hi @devolasvegas - I'm taking over maintenance and development in my personal fork: https://github.com/VinSpee/react-show-more

I'd  love to address this there.

Thanks!
