### ISSUE TITLE
CodeSandbox demo is broken

### ISSUE THREAD

**Issue by newyork-anthonyng** [tedconf/react-show-more#2]
The build seems to be broken. I noticed this when looking at the [CodeSandbox demo](https://codesandbox.io/s/xjykw83n7z). It was saying that it couldn't find the module for `react-show-more`.

I ran `npm install @tedconf/react-show-more`. I looked inside the `package.json`, and the `main` field was pointing to `dist/react-show-more-list.js`.

There is no `dist/react-show-more-list.js` , but there is a `dist/react-show-more.min.js`.

When I renamed `dist/react-show-more.min.js` to `dist/react-show-more-list.js`, the issue is fixed.

**Comment by VinSpee** [comment]
@newyork-anthonyng thanks so much for the report. I have released a fix - the bundler was actually outputting files to a subdirectory because the package is scoped.

all good now!

https://codesandbox.io/s/xjykw83n7z
