### ISSUE TITLE
Add "infinite scroll" example into CodeSandbox

### ISSUE THREAD

**Issue by newyork-anthonyng** [tedconf/react-show-more#4]
Do you think it'd be valuable to add an "infinite scroll" example into CodeSandbox?

I feel like something like [this demo](https://codesandbox.io/s/q9oxzlnj49) might be useful. It's a common pattern that some websites use, and would show how flexible `react-show-more` is.

**Comment by VinSpee** [comment]
Sounds like it could be helpful. I’d love to accept a PR!
